---
- name: install | add docker gpg key
  apt_key:
    keyserver: pgp.mit.edu
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: install | add docker apt repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: install | render defaults
  template:
    src: defaults
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644

- name: install | install docker engine
  apt:
    name: docker-engine
    state: present