---
- name: install | create docker group
  group: name=docker

- name: install | run install script
  shell: curl -sSL https://get.docker.com/ | sh

- name: install | render defaults
  template: src=defaults dest=/etc/default/docker owner=root group=root
  register: render_defaults_result

- name: install | reload daemon
  service: name=docker state=reloaded
  when: render_defaults_result.changed

